# Generated by Django 5.2.7 on 2025-11-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="midtrans_token",
            new_name="midtrans_snap_token",
        ),
        migrations.AddField(
            model_name="order",
            name="midtrans_retry",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Jumlah percobaan pembuatan transaksi Midtrans",
                verbose_name="Midtrans Retry Counter",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="midtrans_snap_token",
            field=models.CharField(
                blank=True,
                help_text="Token Snap terakhir yang diterbitkan untuk pesanan ini",
                max_length=255,
                null=True,
                verbose_name="Midtrans Snap Token",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="midtrans_order_id",
            field=models.CharField(
                blank=True,
                help_text="ID unik yang digunakan untuk transaksi Midtrans",
                max_length=50,
                null=True,
                verbose_name="Midtrans Order ID",
            ),
        ),
    ]
